---
abstract: 'Parse PGN files by using `pgn-extract`'
author:
  - 'Mitsuhiro Nakamura E<lt>m.nacamura@gmail.comE<gt>'
build_requires:
  File::Basename: '0'
  File::Which: '0'
  Module::Build::Pluggable::CPANfile: '0.05'
  Test::More: '0'
configure_requires:
  Module::Build: '0'
  Module::Build::Pluggable: '0'
  Module::Build::Pluggable::CPANfile: '0.05'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Chess-PGN-Extract
provides:
  Chess::PGN::Extract:
    file: lib/Chess/PGN/Extract.pm
    version: '0.01'
  Chess::PGN::Extract::Stream:
    file: lib/Chess/PGN/Extract/Stream.pm
requires:
  Carp: '0'
  Data::Dump: '0'
  Encode: '0'
  Exporter::Tiny: '0'
  File::Temp: '0'
  IO::Handle: '0'
  JSON::XS: '0'
  Sys::Cmd: '0'
  Try::Tiny: '0'
  perl: '5.008001'
version: '0.01'
